excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  ignores_function_declarations: true
  ignores_comments: true
